export const products = [
  {
    id: 1,
    name: 'Pizza Margherita',
    price: 12.99,
    ingredients: 'Tomato sauce, mozzarella cheese, fresh basil',
    img: '../assets/Page3-Menu/pizza_margherita.jpg',
    available: true,
    quantity: 1,
    description:
      'Our classic Pizza Margherita is a delightful blend of simple yet flavorful ingredients. The base of tomato sauce and mozzarella cheese provides the perfect canvas for the freshness of basil leaves to shine. A true Italian classic that never goes out of style.',
  },
  {
    id: 2,
    name: 'Pizza Inferno',
    price: 14.99,
    ingredients: 'Tomato sauce, mozzarella cheese, spicy pepperoni, jalapeños',
    img: '../assets/Page3-Menu/pizza_inferno.jpg',
    available: true,
    quantity: 1,
    description:
      "For those who crave a little heat, our Pizza Inferno is the perfect choice. This fiery delight combines the richness of tomato sauce and mozzarella cheese with the bold flavors of spicy pepperoni and jalapeños. It's a spicy pizza lover's dream.",
  },
  {
    id: 3,
    name: 'Pizza Prosciutto',
    price: 13.99,
    ingredients: 'Tomato sauce, mozzarella cheese, prosciutto, arugula',
    img: '../assets/Page3-Menu/pizza_prosciutto.jpg',
    available: true,
    quantity: 1,
    description: `Experience the perfect balance of flavors with our Pizza Prosciutto. This pizza features the classic combination of tomato sauce and mozzarella cheese, topped with slices of delicate prosciutto and fresh arugula. It's a slice of Italy on your plate.`,
  },
  {
    id: 4,
    name: 'Pizza Capricciosa',
    price: 15.99,
    ingredients: 'Tomato sauce, mozzarella cheese, ham, artichokes, olives',
    img: '../assets/Page3-Menu/pizza_capricciosa.jpg',
    available: true,
    quantity: 1,
    description:
      'The Pizza Capricciosa is a true masterpiece of flavor and texture. It starts with a base of tomato sauce and mozzarella cheese and is elevated with the addition of ham, artichokes, and olives. Each bite is a journey through the Mediterranean.',
  },
  {
    id: 5,
    name: 'Penne al Gorgonzola',
    price: 11.99,
    ingredients: 'Penne pasta, gorgonzola cheese sauce, walnuts',
    img: '../assets/Page3-Menu/penne_gorgonzola.jpg',
    available: true,
    quantity: 1,
    description: `Indulge in the creamy elegance of Penne al Gorgonzola. This dish combines perfectly cooked penne pasta with a rich gorgonzola cheese sauce and a hint of crunch from walnuts. It's a harmonious blend of flavors and textures.`,
  },
  {
    id: 6,
    name: 'Spaghetti Carbonara',
    price: 12.99,
    ingredients: 'Spaghetti, eggs, pancetta, Pecorino Romano cheese',
    img: '../assets/Page3-Menu/spaghetti_carbonara.jpg',
    available: true,
    quantity: 1,
  },
  {
    id: 7,
    name: 'Tiramisu',
    price: 6.99,
    ingredients: 'Mascarpone cheese, coffee-soaked ladyfingers, cocoa powder',
    img: '../assets/Page3-Menu/tiramisu.jpg',
    available: true,
    quantity: 1,
  },
  {
    id: 8,
    name: 'Bruschetta',
    price: 9.99,
    ingredients: 'Grilled bread, fresh tomatoes, garlic, basil',
    img: '../assets/Page3-Menu/bruschetta.jpg',
    available: true,
    quantity: 1,
  },
  {
    id: 9,
    name: 'Risotto ai Funghi',
    price: 14.99,
    ingredients: 'Arborio rice, mushrooms, Parmesan cheese, white wine',
    img: '../assets/Page3-Menu/risotto_funghi.jpg',
    available: false,
    quantity: 1,
  }
];
